'use strict';
const $=id=>document.getElementById(id);let catalog;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const val=id=>$(id).value.trim();
function msg(t,ok=false){$('message').textContent=t;$('message').className='message'+(ok?' success':'');}
function fmt(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
const now=new Date(),end=new Date();end.setFullYear(end.getFullYear()+1);$('validFrom').value=fmt(now);$('validUntil').value=fmt(end);$('ownerValidFrom').value=fmt(now);const ownerEnd=new Date();ownerEnd.setFullYear(ownerEnd.getFullYear()+10);$('ownerValidUntil').value=fmt(ownerEnd);
async function keyStatus(){const s=await window.masterApi.keyStatus();$('keyStatus').textContent=s.installed?'Master Key installed':'Master Key not installed';$('keyStatus').className=s.installed?'key-ok':'key-missing';$('removeKeyBtn').disabled=!s.installed;return s.installed;}
function renderFeatures(){const edition=catalog.editions.find(x=>x.id===$('editionId').value)||catalog.editions[0];const enabled=new Set(edition.features);const fixed=edition.id==='lite';$('features').dataset.fixedEdition=fixed?'lite':'';$('features').innerHTML=catalog.features.map(f=>`<label class="feature"><input type="checkbox" data-feature="${esc(f.id)}" ${enabled.has(f.id)?'checked':''} ${fixed?'disabled':''}><span><b>${esc(f.label)}</b><small>${esc(f.group)}</small></span></label>`).join('');$('productDisplayName').value=edition.displayName;}
(async()=>{catalog=await window.masterApi.catalog();$('editionId').innerHTML=catalog.editions.map(e=>`<option value="${e.id}">${e.name}</option>`).join('');renderFeatures();$('version').textContent=`Master License Manager v${catalog.suiteVersion} · Engine ${catalog.engineVersion}`;await keyStatus();})();
$('editionId').addEventListener('change',renderFeatures);
$('importKeyBtn').addEventListener('click',async()=>{try{const r=await window.masterApi.importKey();if(!r.canceled)msg('Master Key imported.',true);await keyStatus();}catch(e){msg(e.message);}});
$('removeKeyBtn').addEventListener('click',async()=>{try{const r=await window.masterApi.removeKey();if(r.removed)msg('Master Key removed from this computer.',true);await keyStatus();}catch(e){msg(e.message);}});
$('form').addEventListener('submit',async e=>{e.preventDefault();$('result').classList.add('hidden');try{if(!(await keyStatus()))throw new Error('Import the Master Key first.');const features=[...document.querySelectorAll('[data-feature]:checked')].map(x=>x.dataset.feature);const doc=await window.masterApi.generate({enrollmentCode:val('enrollmentCode'),customerName:val('customerName'),customerId:val('customerId'),entitlementLabel:val('entitlementLabel'),seats:Number(val('seats')),validFrom:val('validFrom'),validUntil:val('validUntil'),editionId:val('editionId'),productDisplayName:val('productDisplayName'),features,masterPassword:val('masterPassword')});$('masterPassword').value='';const saved=await window.masterApi.save(doc);if(saved.canceled)return msg('Entitlement generated but not saved.');const p=doc.summary;$('result').innerHTML=`<div class="title"><span>✓</span><h2>Entitlement Generated</h2></div><div class="result-grid"><b>Customer</b><span>${esc(p.customerName)}</span><b>Edition</b><span>${esc(p.productDisplayName)}</span><b>Seats</b><span>${p.seats}</span><b>Features</b><span>${p.featuresCount}</span><b>Host</b><span>${esc(p.licenseHostId)}</span><b>File</b><span>${esc(saved.filePath)}</span></div>`;$('result').classList.remove('hidden');msg('Entitlement generated.',true);}catch(err){$('masterPassword').value='';msg(err.message||String(err));}});
$('generateOwnerBtn').addEventListener('click',async()=>{try{if(!(await keyStatus()))throw new Error('Import the Master Key first.');const password=$('ownerMasterPassword').value;if(!password)throw new Error('Enter the Master Password.');const doc=await window.masterApi.generateOwner({ownerName:$('ownerName').value.trim(),validFrom:$('ownerValidFrom').value,validUntil:$('ownerValidUntil').value,masterPassword:password});$('ownerMasterPassword').value='';const saved=await window.masterApi.saveOwner(doc);if(!saved.canceled)msg('Owner Universal License generated.',true);}catch(e){$('ownerMasterPassword').value='';msg(e.message||String(e));}});
